FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt gunicorn

COPY . .

EXPOSE 5000

# Usando Gunicorn para produção em vez do servidor de dev do Flask
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"]